#Digital Scene
#Yareli Vergara, Matti Wachalski, and Diego Torres

#Initialization

import turtle
yareli = turtle.Turtle()
yareli.speed(10)
yareli.pensize(10)


Matti = turtle.Turtle()
Matti.speed(10)
Matti.pensize(10)


diego = turtle.Turtle()
diego.speed(10)
diego.pensize(10)
turtle.colormode(255)


#Function



def make_plantingPlot(color): #makes the dirt plot (Yareli) 
    yareli.up()
    yareli.goto(950,-300)
    yareli.pd()
    yareli.begin_fill()
    yareli.pencolor(color)
    yareli.fillcolor(color)
    yareli.left(180)
    yareli.forward(1000)
    yareli.left(25)
    yareli.forward(600)
    yareli.left(155)
    yareli.forward(2000)
    yareli.end_fill()


def make_Grass(color): #makes part of the grass (Yareli)
    yareli.up()
    yareli.goto(-960,-380)
    yareli.pd()
    yareli.begin_fill()
    yareli.pencolor(color)
    yareli.fillcolor(color)
    yareli.left(13)
    yareli.forward(1300)
    yareli.left(77)
    yareli.forward(80) 
    yareli.right(90)
    yareli.forward(700) 
    yareli.right(90)
    yareli.forward(285) 
    yareli.right(90)
    yareli.forward(1050)
    yareli.left(25)
    yareli.forward(2000)
    yareli.end_fill()


def make_dirtTrail(color): #makes the dirt trail (Yareli) #Parameter determines the color
    yareli.up()
    yareli.goto(-957,-370) 
    yareli.pd()
    yareli.begin_fill()
    yareli.pencolor(color)
    yareli.fillcolor(color)
    yareli.right(192)
    yareli.forward(1295) 
    yareli.left(78)
    yareli.forward(72)
    yareli.left(80)
    yareli.forward(300)
    yareli.right(130)
    yareli.forward(150)
    yareli.left(139)
    yareli.forward(150)
    yareli.left(35)
    yareli.forward(200)
    yareli.left(135)
    yareli.forward(400)
    yareli.right(160)
    yareli.forward(1200)
    yareli.end_fill()
    

def make_Grass2(color): #makes a part of the grass(Yareli) #Parameter determines the color
    yareli.left(180)
    yareli.up()
    yareli.goto(-960, -245)
    yareli.pd()
    yareli.begin_fill()
    yareli.pencolor(color)
    yareli.fillcolor(color)
    yareli.forward(1145)
    yareli.left(160)
    yareli.forward(373)
    yareli.right(134)
    yareli.forward(207)
    yareli.left(144)
    yareli.forward(3000)
    yareli.left(90)
    yareli.forward(3000)
    yareli.end_fill()



def make_Sun(size, color): #makes the sun(Matti) #Parameter determines the size and color
    Matti.penup()
    Matti.goto(-800,350)
    Matti.pendown()
    Matti.dot(size, color)
    
def make_Windows(color, x,y): #makes the windows(Matti) #Parameter determines the color and x, y coordinates
    Matti.setheading(0)
    Matti.color(color)
    Matti.begin_fill()
    Matti.penup()
    Matti.goto(x,y)
    Matti.pendown()
    for i in range(4):
        Matti.forward(50)
        Matti.left(90)
    Matti.end_fill()

def make_House(color): #makes the house(Matti) #Parameter determines color
    Matti.color(color)
    Matti.begin_fill()
    Matti.penup()
    Matti.goto(600,0)
    Matti.pendown()
    for i in range(4):
        Matti.forward(300)
        Matti.left(90)
    Matti.end_fill()
    
def make_topOfHouse(color): #makes the top of the house(Matti) #Parameter determines color
    Matti.goto(600,300)
    Matti.color(color)
    Matti.begin_fill()
    Matti.goto(600,300)
    Matti.left(30)
    Matti.forward(175)
    Matti.right(60)
    Matti.forward(175)
    Matti.right(60)
    Matti.end_fill()
    
def make_chimneyTower(color): #makes the chimney tower(Matti) #Parameter determines color
    Matti.penup()
    Matti.setheading(90)
    Matti.goto(500,0)
    Matti.color(color)
    Matti.begin_fill()
    Matti.pendown()
    Matti.penup()
    Matti.forward(300)
    Matti.left(90)
    Matti.pendown()
    Matti.forward(50)
    Matti.left(90)
    Matti.forward(300)
    Matti.left(90)
    Matti.forward(50)
    Matti.end_fill()

def make_topOfChimneyTower(color): #makes the top of the chimney tower(Matti) #Parameter determines color
    Matti.color(color)
    Matti.left(90)
    Matti.forward(300)
    Matti.begin_fill()
    Matti.left(60)
    Matti.forward(30)
    Matti.left(60)
    Matti.forward(30)
    Matti.left(150)
    Matti.forward(50)
    Matti.end_fill()
    Matti.penup()

#Diego's code
def draw_cloud(x,y): #makes the clouds(Diego) #Parameter determines x, y coordinates
    diego.penup()
    diego.goto(x,y)
    diego.pendown()
    diego.color((217, 217, 217))
    diego.begin_fill()
    diego.forward(200)
    diego.circle(50,180)
    diego.left(270)
    diego.circle(60,120)
    diego.left(240)
    diego.circle(70,200)
    diego.left(230)
    diego.circle(68,180)
    diego.left(20)
    diego.forward(150)
    diego.left(90)
    diego.forward(10)
    diego.end_fill()

def draw_square(y,color):#makes a square to use for other functions #Parameter determines color and y coordinate
    diego.penup()
    diego.goto(-960,y)
    diego.pendown()
    diego.color(color)
    diego.begin_fill()
    for i in range(2): 
        diego.forward(2000)
        diego.right(90)
        diego.forward(75)
        diego.right(90)
    diego.end_fill()

def draw_tree(x,y,): #makes the first tree(Diego) #Parameter determines x, y coordinates
    diego.penup()
    diego.goto(x,y)
    diego.pendown()
    diego.color((128, 64, 0))
    diego.circle(75,85)
    diego.circle(1000,10)
    diego.penup()
    diego.goto(x,y)
    diego.begin_fill()
    diego.pendown()
    diego.right(94.5)
    diego.forward(250)
    diego.circle(75,-85)
    diego.circle(1000,-10)
    diego.right(83)
    diego.forward(107)
    diego.end_fill()
   
def draw_tree2(x,y): #makes the second tree(Diego) #Parameter determines x, y coordinates
    diego.begin_fill()
    diego.color((128, 64, 0))
    diego.left(95)
    diego.penup()
    diego.goto(x,y)
    diego.begin_fill()
    diego.pendown()
    diego.right(94.5)
    diego.forward(250)
    diego.circle(75,-85)
    diego.circle(1000,-10)
    diego.right(83)
    diego.forward(107)
    diego.left(270)
    diego.circle(1000,-10)
    diego.circle(75,-85)
    diego.end_fill()
    diego.pensize(100)
    diego.penup()
    diego.goto(x,y)
    diego.color((0, 102, 0))
    diego.circle(75,85)
    diego.circle(1000,10)
    diego.left(90)
    diego.forward(20)
    diego.pendown()
    diego.left(180)
    diego.circle(60,-45)
    diego.left(90)
    diego.circle(45,-180)
    diego.left(60)
    diego.circle(45,-65)
    diego.left(90)
    diego.circle(45,-180)
    diego.left(90)
    diego.circle(45,-45)
    diego.left(90)
    diego.circle(45,-180)
    diego.left(120)
    diego.circle(55,-45)
    diego.left(90)
    diego.circle(45,-180)
    diego.left(120)
    diego.circle(45,-180)
    diego.left(90)
    diego.circle(45,-45)
    diego.left(40)
    diego.circle(45,-90)
    diego.left(40)
    diego.circle(45,-90)
    diego.left(40)
    diego.circle(45,-30)
    diego.left(211.70)
    diego.forward(130)
    diego.left(270)
    diego.forward(125)
    diego.left(270)
    diego.forward(175)
    diego.left(270)
    diego.forward(75)
    diego.left(275)
    diego.forward(100)

def draw_fence_post(): #makes part of the fence(Diego)
    diego.begin_fill()
    diego.color((128, 64, 0))
    diego.forward(50)
    diego.left(90)
    diego.forward(100)
    diego.left(45)
    diego.forward(40)
    diego.left(90)
    diego.forward(40)
    diego.left(45)
    diego.forward(100)
    diego.left(180)
    diego.forward(75)
    diego.left(90)
    diego.forward(50)
    diego.left(270)
    diego.forward(15)
    diego.left(270)
    diego.forward(50)
    diego.left(270)
    diego.forward(50)
    diego.left(270)
    diego.forward(50)
    diego.left(90)
    diego.forward(15)
    diego.left(90)
    diego.forward(50)
    diego.left(180)
    diego.end_fill()
  
  
def draw_fence(x,y): #makes the fence(diego) #Parameter determines x, y coordinates
    diego.pu()
    diego.goto(x,y)
    diego.pd() 
    draw_fence_post()
    diego.forward(100)
    diego.left(180)
    draw_fence_post()
    diego.forward(100)
    diego.left(180)
    draw_fence_post()
    diego.forward(100)
    diego.left(180)
    draw_fence_post()
    diego.forward(100)
    diego.left(180)
    draw_fence_post()
    diego.forward(100)
    diego.left(180)
    draw_fence_post()
    diego.forward(100)
    diego.left(180)
    draw_fence_post()
    diego.forward(100)
    diego.left(180)
    diego.begin_fill()
    diego.color((128, 64, 0))
    diego.forward(50)
    diego.left(90)
    diego.forward(100)
    diego.left(45)
    diego.forward(40)
    diego.left(90)
    diego.forward(40)
    diego.left(45)
    diego.forward(100)
    diego.end_fill()

def draw_sky(): #makes the sky(Diego)
    draw_square(510,(51, 214, 255))
    draw_square(435,(102, 224, 255))
    draw_square(370,(128, 229, 255))
    draw_square(295,(153, 235, 255))
    draw_square(225,(179, 240, 255))
    draw_square(150,(204, 245, 255))
    draw_square(75,(230, 250, 255))
    draw_cloud(500,250)
    diego.right(90)
    draw_cloud(-600,200)

def draw_all_diego():#makes all of diego's functions
    draw_sky()
    diego.right(90)
    draw_tree2(0,0)
    diego.pensize(1)
    diego.left(180)
    draw_fence(-200,-150)

def make_allYareli(): #makes all of Yareli's functions
    make_plantingPlot("#663300")
    make_Grass("#006600")
    make_dirtTrail("#996600")
    make_Grass2("#006600")

    
def make_allMatti(): #makes all of Matti's functions
    make_Sun(100,"yellow")
    make_House("yellow")
    make_topOfHouse("red")
    make_Windows("lightblue", 635,35)
    make_Windows("lightblue", 815,35)
    make_Windows("lightblue", 635,160)
    make_Windows("lightblue", 815,160)
    make_chimneyTower("grey")
    make_topOfChimneyTower("red")

    
def draw_Garden(): #Makes the whole garden
    make_allYareli()
    draw_all_diego()
    make_allMatti()


#Main
draw_Garden()
